name = "my-cloudflare-workers-demo"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-01-31"
account_id = 'f265eb5472bd1a7e5e077918b6f56a06'
